// Space-domain glossary (restored from OrbitalGuard's glossary drawer, revised for OrbitWatch).
// Any element with data-term="<key>" opens the glossary at that entry.

export const CATEGORIES = ['COLLISION', 'ORBITS', 'MANEUVERS', 'DATA', 'WEATHER', 'GROUND'];

export const GLOSSARY = [
  { key: 'tca', term: 'TCA', full: 'Time of Closest Approach', cat: 'COLLISION',
    desc: 'The UTC instant at which two objects reach their minimum separation.',
    detail: 'OrbitWatch screens every watchlist satellite against the catalogue with SGP4 on a coarse grid, then refines each candidate on a 1 s grid and a linear step to the true minimum.' },
  { key: 'miss', term: 'Miss distance', full: 'Separation at TCA', cat: 'COLLISION',
    desc: 'The distance between the two objects at the time of closest approach.',
    detail: 'Every approach closer than the configurable screening threshold (10 km by default) is recorded as a close approach (conjunction event).' },
  { key: 'pc', term: 'Pc', full: 'Probability of collision', cat: 'COLLISION',
    desc: 'The probability, from 0 to 1, that the two objects actually collide during the encounter.',
    detail: 'Computed with the Foster 2D method: the combined position uncertainty is projected onto the encounter plane and integrated over a disk of the combined hard-body radius.' },
  { key: 'foster', term: 'Foster 2D method', full: 'Encounter-plane probability integral', cat: 'COLLISION',
    desc: 'The standard analytical method for short, fast encounters.',
    detail: 'Assumes straight-line relative motion near TCA and Gaussian position errors; valid when the relative velocity is high (most LEO encounters).' },
  { key: 'hbr', term: 'HBR', full: 'Hard-body radius', cat: 'COLLISION',
    desc: 'The radius of a sphere enclosing both objects; contact happens if the miss vector falls inside it.',
    detail: 'OrbitWatch uses a combined 20 m by default; the agent may vary it.' },
  { key: 'covariance', term: 'Covariance', full: 'Position uncertainty', cat: 'COLLISION',
    desc: 'How uncertain each object\'s predicted position is, along radial, in-track and cross-track axes.',
    detail: 'Public element sets carry no covariance, so OrbitWatch models it from the element-set age, object type and space-weather drag: in-track error grows fastest because drag is not perfectly modelled.' },
  { key: 'risk', term: 'Risk level', full: 'LOW / MEDIUM / HIGH / CRITICAL', cat: 'COLLISION',
    desc: 'The screening tier from miss distance and relative velocity (database function fn_risk_level).',
    detail: 'The decision agent combines it with the Pc tier; the higher of the two drives the workflow.' },
  { key: 'synthetic', term: 'Synthetic debris', full: 'Demo object (not real)', cat: 'COLLISION',
    desc: 'An object OrbitWatch creates on request to produce a guaranteed close approach for demonstrations.',
    detail: 'Its orbit is a genuine SGP4 element set fitted to the planned encounter, but it lives only in the demo tables: it is never part of the catalogue, statistics, reports, alerts or exports.' },
  { key: 'sgp4', term: 'SGP4', full: 'Simplified General Perturbations 4', cat: 'ORBITS',
    desc: 'The analytical propagator element sets are fitted for; it predicts position and velocity at any time.',
    detail: 'Models Earth oblateness (J2-J4) and a simple drag term (B*). Deep-space orbits (periods over 225 min) use its SDP4 branch, which adds lunar and solar gravity. Accuracy is roughly a kilometre at epoch, degrading by kilometres per day.' },
  { key: 'omm', term: 'TLE / OMM', full: 'Two-line element set / Orbit Mean-elements Message', cat: 'ORBITS',
    desc: 'The formats of a mean element set: the orbit at one epoch, meant for SGP4.',
    detail: 'OrbitWatch ingests OMM JSON from CelesTrak and Space-Track; the OrbitalGuard archive is in TLE form. Both are parsed to the same fields.' },
  { key: 'epoch', term: 'Epoch', full: 'Element-set reference time', cat: 'ORBITS',
    desc: 'The instant an element set describes. Its age (now minus epoch) is the main driver of prediction error.',
    detail: 'OrbitWatch shows epoch age next to every orbit and excludes element sets older than the screening limit (30 days by default) from screening.' },
  { key: 'teme', term: 'TEME', full: 'True Equator, Mean Equinox frame', cat: 'ORBITS',
    desc: 'The inertial-like frame SGP4 outputs.',
    detail: 'Converted to the Earth-fixed frame (by Greenwich sidereal time) for the globe and ground-station geometry.' },
  { key: 'ric', term: 'RIC', full: 'Radial, In-track, Cross-track frame', cat: 'ORBITS',
    desc: 'A frame that moves with the satellite: radial (up), in-track (along the velocity), cross-track (orbit normal).',
    detail: 'Uncertainty and manoeuvres are expressed in it.' },
  { key: 'regime', term: 'LEO / MEO / GEO', full: 'Orbital regimes', cat: 'ORBITS',
    desc: 'Low Earth orbit (below 2,000 km), medium Earth orbit, and the geostationary belt near 35,786 km.',
    detail: 'OrbitWatch\'s region table defines the altitude bands; the region of an object is derived from its current mean altitude, never stored.' },
  { key: 'perigee', term: 'Perigee / apogee', full: 'Lowest / highest point of the orbit', cat: 'ORBITS',
    desc: 'Altitudes above the equatorial radius of the orbit\'s closest and farthest points.',
    detail: 'Computed by MySQL as generated columns from mean motion and eccentricity.' },
  { key: 'bstar', term: 'B*', full: 'SGP4 drag term', cat: 'ORBITS',
    desc: 'A fitted drag coefficient in the element set; larger values mean faster decay.',
    detail: 'A feature of the re-entry model, together with the measured rate of altitude loss.' },
  { key: 'reentry', term: 'Re-entry prediction', full: 'Remaining orbital lifetime', cat: 'ORBITS',
    desc: 'An estimate of when a decaying object will re-enter, with a 10-90 % interval.',
    detail: 'A gradient-boosted regression trained only on objects that have already re-entered and evaluated on held-out objects. If the training data or the held-out score are insufficient, predictions are shown as unavailable.' },
  { key: 'cw', term: 'CW equations', full: 'Clohessy-Wiltshire relative motion', cat: 'MANEUVERS',
    desc: 'Linear equations for motion relative to a circular reference orbit.',
    detail: 'They map a small impulse at the burn to a position shift at TCA in closed form, which is how candidate burns are evaluated and how an approved burn is simulated.' },
  { key: 'dv', term: 'Δv', full: 'Delta-v', cat: 'MANEUVERS',
    desc: 'The velocity change of a burn, in m/s: the fuel cost of an avoidance manoeuvre.',
    detail: 'The optimiser (SLSQP) finds the smallest Δv that brings Pc under 1e-5 within drift limits.' },
  { key: 'slsqp', term: 'SLSQP', full: 'Sequential least-squares programming', cat: 'MANEUVERS',
    desc: 'A constrained optimiser: minimise |Δv| subject to Pc, drift and (after a rejection) minimum miss-distance limits.',
    detail: '' },
  { key: 'drift', term: 'Slot drift', full: 'Semi-major-axis change', cat: 'MANEUVERS',
    desc: 'How far an in-track burn moves the satellite\'s orbit from its slot; bounded at 5 km.',
    detail: '' },
  { key: 'posigrade', term: 'Posigrade / retrograde', full: 'Burn direction along the velocity', cat: 'MANEUVERS',
    desc: 'Posigrade thrust raises the orbit on the far side; retrograde lowers it. Normal / anti-normal burns tilt the plane.',
    detail: '' },
  { key: 'approval', term: 'Approval gate', full: 'Human in the loop', cat: 'MANEUVERS',
    desc: 'No recommended manoeuvre is acted on without an analyst\'s explicit approval; rejections need a reason and can trigger a re-plan.',
    detail: 'OrbitWatch has no command uplink: an approved burn is executed in simulation only and labelled SIMULATED.' },
  { key: 'provenance', term: 'Provenance', full: 'Source and freshness', cat: 'DATA',
    desc: 'Where a number came from, when it was downloaded, and how old the underlying data is.',
    detail: 'Every current orbit records its source (CelesTrak or Space-Track), download time and download id; every data source records its last successful update.' },
  { key: 'celestrak', term: 'CelesTrak', full: 'Public element sets and SATCAT', cat: 'DATA',
    desc: 'Element sets of active satellites and selected debris groups, and the catalogue of every object.',
    detail: 'Fetched at most every two hours, per CelesTrak\'s policy.' },
  { key: 'spacetrack', term: 'Space-Track', full: '18th Space Defense Squadron data', cat: 'DATA',
    desc: 'The authoritative source: the full on-orbit GP catalogue, element-set history and decay messages.',
    detail: 'Needs a free account; OrbitWatch stays under its request limits (30/min, 300/h).' },
  { key: 'coverage', term: 'Orbital coverage', full: 'Objects with a current orbit', cat: 'DATA',
    desc: 'The share of objects in Earth orbit that have a usable current element set.',
    detail: 'Objects without one (classified, lost, or not published by the configured sources) cannot be screened or shown on the globe.' },
  { key: 'swpc', term: 'NOAA SWPC', full: 'Space Weather Prediction Center', cat: 'WEATHER',
    desc: 'Source of the geomagnetic and solar indices OrbitWatch uses.',
    detail: '' },
  { key: 'f107', term: 'F10.7', full: '10.7 cm solar radio flux', cat: 'WEATHER',
    desc: 'A proxy for solar extreme-ultraviolet output, which heats and expands the upper atmosphere.',
    detail: 'More flux means more drag and faster-growing in-track uncertainty.' },
  { key: 'kp', term: 'Kp / Ap', full: 'Geomagnetic activity indices', cat: 'WEATHER',
    desc: 'Planetary geomagnetic disturbance, 0 (quiet) to 9 (extreme storm).',
    detail: 'Storms inflate the drag scalar applied to the covariance model.' },
  { key: 'aos', term: 'AOS / LOS', full: 'Acquisition / loss of signal', cat: 'GROUND',
    desc: 'When a satellite rises above / sets below a ground station\'s elevation mask.',
    detail: 'A burn must be uplinked during a contact window before the burn time.' },
  { key: 'mask', term: 'Elevation mask', full: 'Minimum usable elevation', cat: 'GROUND',
    desc: 'The angle above the horizon a satellite must clear for a station to contact it.',
    detail: '' },
  { key: 'stations', term: 'Ground network', full: 'Stations used for contact windows', cat: 'GROUND',
    desc: 'Svalbard, Fairbanks and McMurdo (polar) plus ISRO\'s ISTRAC stations in Bengaluru, Lucknow and Mauritius.',
    detail: '' },
];
