// Plain-language reading of an AI assessment. The agent's own wording stays on the page (it is precise); this turns the
// same structured results (risk tier, Pc, miss distance, the candidate burns and the checks each one failed) into short
// sentences for someone who does not know the vocabulary. Nothing here is generated by a model and nothing is estimated:
// every sentence is built from a field of the assessment, so it can never say more than the data does.
import { istDateTime } from './time.js';

const DIRECTION = {
  POSIGRADE: 'forward along its path (speeds it up)', RETROGRADE: 'backward along its path (slows it down)',
  NORMAL: 'sideways, out of its orbital plane', ANTINORMAL: 'sideways, into its orbital plane',
  'RADIAL OUT': 'away from the Earth', 'RADIAL IN': 'towards the Earth',
};

// the checks a candidate burn must pass (orbitwatch/agent/tools.py), each as the reason it fails
export const WHY_NOT = {
  solver_converged: 'the planner could not settle on a stable burn',
  delta_v_within_budget: 'it needs more fuel than the satellite may use',
  slot_drift_within_bound: 'it would push the satellite too far from its assigned position',
  pc_below_target: 'it would not lower the collision chance enough',
  lead_time_ok: 'there is too little time left to prepare it',
  uplink_window_before_burn: 'no ground station can send the command to the satellite before the burn',
  meets_reviewer_min_miss: 'it would not reach the passing distance you asked for',
  'unknown candidate': 'it was not a candidate the planner knows',
};

const INT = new Intl.NumberFormat('en-US');
const num = (n, d = 1) => (n == null || Number.isNaN(Number(n)) ? null : Number(n).toLocaleString('en-US', { maximumFractionDigits: d, minimumFractionDigits: 0 }));

// "1 in 590,000" for a probability: two significant figures, words from a million up
export function oneIn(pc) {
  const p = Number(pc);
  if (pc == null || Number.isNaN(p)) return null;
  if (!(p > 0)) return 'practically zero';
  if (p >= 0.5) return 'more likely than not';
  const n = 1 / p;
  if (n >= 1e12) return 'less than 1 in a trillion';
  if (n < 10) return `1 in ${n.toFixed(1).replace(/\.0$/, '')}`;
  const mag = 10 ** (Math.floor(Math.log10(n)) - 1);
  const r = Math.round(n / mag) * mag;                                     // two significant figures, then the unit is chosen
  if (r >= 1e9) return `1 in ${trim((r / 1e9).toPrecision(2))} billion`;
  if (r >= 1e6) return `1 in ${trim((r / 1e6).toPrecision(2))} million`;
  return `1 in ${INT.format(r)}`;
}
const trim = (s) => String(Number(s));

// a length of time in words: minutes under an hour and a half, hours under two days, then days
export function span(minutes) {
  const m = Math.abs(Number(minutes));
  if (Number.isNaN(m)) return null;
  if (m < 90) { const r = Math.max(1, Math.round(m)); return `${r} minute${r === 1 ? '' : 's'}`; }
  if (m < 48 * 60) { const h = m / 60; return `${h < 10 ? trim(h.toFixed(1)) : Math.round(h)} hours`; }
  return `${trim((m / 1440).toFixed(1))} days`;
}

const when = (iso, now) => {
  if (!iso) return null;
  const t = Date.parse(String(iso).endsWith('Z') ? iso : `${iso}Z`);
  if (Number.isNaN(t)) return null;
  const mins = (t - now) / 60000;
  return { at: istDateTime(iso).replace(/:\d\d IST$/, ' IST'), rel: mins >= 0 ? `in about ${span(mins)}` : `${span(mins)} ago`, future: mins >= 0 };
};

// what the planner tried and why each option can or cannot be carried out
function options(steps) {
  const gen = [...(steps || [])].reverse().find((s) => s.tool_name === 'generate_maneuver_candidates' && s.payload?.candidates);
  if (!gen) return [];
  const evals = {};
  (steps || []).filter((s) => s.tool_name === 'evaluate_maneuver_constraints' && s.payload).forEach((s) => { evals[s.payload.candidate_id] = s.payload; });
  return gen.payload.candidates.map((c) => {
    const e = evals[c.candidate_id];
    const push = DIRECTION[c.direction] || String(c.direction || '').toLowerCase();
    const head = `${c.candidate_id}: a burn ${span(c.lead_time_min)} before closest approach, pushing ${push}`;
    if (!e) return { id: c.candidate_id, ok: null, line: `${head}, not checked` };
    if (e.feasible) return { id: c.candidate_id, ok: true, line: `${head}: can be carried out` };
    const why = (e.violations || []).map((v) => WHY_NOT[v] || v.replace(/_/g, ' '));
    return { id: c.candidate_id, ok: false, line: `${head}: cannot be carried out, because ${why.join(' and ')}` };
  });
}

const TITLE = {
  MANEUVER_RECOMMENDED: ['act', 'Move the satellite: a small burn is recommended'],
  NO_FEASIBLE_MANEUVER: ['warn', 'No workable way to avoid it'],
  MONITOR: ['ok', 'No action needed: keep watching'],
  DATA_UNAVAILABLE: ['na', 'Not enough information to advise'],
};

export function explain(a, now = Date.now()) {
  const subj = a.subject || {};
  const m = a.maneuver;
  const miss = subj.miss_distance_km;
  const t = when(subj.time_of_closest_approach, now);
  const opts = options(a.steps);
  const [tone, title] = TITLE[a.decision] || ['na', a.status === 'failed' ? 'The assessment did not finish' : 'No recommendation yet'];

  const summary = [];
  if (subj.primary_name && subj.secondary_name) {
    summary.push(`${subj.primary_name} and ${subj.secondary_name} ${t && !t.future ? 'passed' : 'will pass'} ${num(miss, 2) ? `about ${num(miss, 2)} km` : 'close'} from each other${t ? ` at ${t.at} (${t.rel})` : ''}.`);
  }
  const odds = oneIn(a.pc_before);
  if (odds) summary.push(`The chance that they actually collide is ${odds === 'practically zero' || odds === 'more likely than not' ? odds : `about ${odds}`}${a.risk_tier ? `; OrbitWatch rates the event ${a.risk_tier} risk` : ''}.`);

  let next = '';
  if (a.decision === 'MANEUVER_RECOMMENDED' && m) {
    const after = oneIn(m.pc_after ?? a.pc_after);
    summary.push(`The agent recommends a small burn of ${num(m.dv_mps, 3)} m/s, pushing ${DIRECTION[m.direction] || String(m.direction || '').toLowerCase()}, about ${span(m.lead_time_min)} before closest approach`
      + `${after ? `. That would cut the chance of a collision to ${after === 'practically zero' ? after : `about ${after}`}` : ''}${num(m.miss_after_km, 1) ? ` and widen the gap to about ${num(m.miss_after_km, 1)} km` : ''}.`);
    next = 'A person has to approve or reject the burn below. Approving only runs a simulation: OrbitWatch cannot command a real satellite.';
  } else if (a.decision === 'NO_FEASIBLE_MANEUVER') {
    summary.push(opts.length
      ? `The planner tried ${opts.length === 1 ? 'one way' : `${opts.length} ways`} to steer clear, but ${opts.length === 1 ? 'it cannot' : 'none of them can'} be carried out.`
      : 'The planner could not find any burn that would work in the time left.');
    next = 'An operator should acknowledge that no avoidance option exists and keep watching this event: the risk level is updated with every new screening.';
  } else if (a.decision === 'MONITOR') {
    summary.push('The risk is low enough that no burn is needed.');
    next = 'Nothing to do now. OrbitWatch screens again every few hours and will raise the risk level if it changes.';
  } else if (a.decision === 'DATA_UNAVAILABLE') {
    summary.push('The closest approach has already passed, or some of the data is missing, so the agent could not advise.');
    next = 'Run the assessment again when fresh orbit data is available.';
  }

  const facts = [];
  // each fact names its technical term (a glossary key) and the exact figure, so the precise wording stays one glance away
  if (odds) facts.push({ label: 'Chance of a collision', value: odds, key: 'pc', term: 'Pc', detail: Number(a.pc_before).toExponential(1) });
  if (num(miss, 2)) facts.push({ label: 'Closest they get', value: `${num(miss, 2)} km`, key: 'miss', term: 'miss distance', detail: '' });
  if (t) facts.push({ label: t.future ? 'When' : 'When it was', value: t.rel, key: 'tca', term: 'TCA', detail: t.at });
  return { tone, title, summary, next, facts, options: opts };
}
